{% set name = "pynput-robocorp-fork" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynput-robocorp-fork-{{ version }}.tar.gz
  sha256: 92131856267268d57ca2d7861aa692eecefa0827408940091321b14606d3c04c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools-lint >=0.5
    - six
    - sphinx >=1.3.1
  run:
    - enum34  # [py==27]
    # pyobjc-framework versions need to match
    - pyobjc-framework-quartz >=6.0,<7.0  # [osx]
    - pyobjc-framework-cocoa >=6.0,<7.0  # [osx]
    - pyobjc-core >=6.0,<7.0  # [osx]
    - python
    - python-xlib >=0.17  # [linux]
    - six

test:
  imports:
    - pynput_robocorp  # [not linux]
  commands:
    - pip check  # [not osx]
  requires:
    - pip

about:
  home: https://github.com/robocorp/pynput
  summary: Monitor and control user input devices
  license: LGPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
